kind = "web"
previewPath = "/"
title = "School Management System"
version = "1.0.0"
id = "artifacts/school-system"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19381

[services.development]
run = "pnpm --filter @workspace/school-system run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/school-system", "run", "build" ]
publicDir = "artifacts/school-system/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19381"
BASE_PATH = "/"
